---

- hosts: all
  become: true
  become_method: sudo

  vars:
    monit_services:
      - name: SSHd
        type: process
        target: /var/run/sshd.pid
        start: /usr/sbin/service sshd start
        stop: /usr/sbin/service sshd stop

      - name: Internet
        type: host
        target: google.com
        rules:
          - "if failed port 443 type tcpSSL protocol http then alert"

      - name: "{{ ansible_hostname }}"
        type: system
        rules:
          - "if loadavg (1min) > 5 then alert"
          - "if loadavg (5min) > 2 then alert"
          - "if memory usage > 75% then alert"
          - "if swap usage > 25% then alert"
          - "if cpu usage (user) > 70% for 8 cycles then alert"
          - "if cpu usage (system) > 40% for 8 cycles then alert"
          - "if cpu usage (wait) > 20%  for 8 cycles then alert"

      - name: "Disk : /dev"
        type: filesystem
        target: "/dev"
        rules:
          - "if space usage > 60% for 5 times within 15 cycles then alert"
          - "if space usage > 80% then alert"
          - "if inode usage > 30000 then alert"

    monit_webinterface_enabled: false
    mmonit_server_ip: 192.168.64.52

  roles:
    - role: '{{playbook_dir}}'